### ISSUE TITLE
Testing without TF

### ISSUE THREAD

**Issue by asagot** [UCLA-VAST/FlexCNN#21]
If I wanted to run the kernel without TF, would I just set CIN = RGB 384x384 raw image in the host.cpp file?

**Comment by atefehsz** [comment]
You don't need to modify the codes in the `SDx_project` folder for that. It can run without TF. Also, both the executable code and the bitstream are already available [here](https://github.com/UCLA-VAST/FlexCNN/tree/master/libsacc/config).

**Comment by asagot** [comment]
Thank you for the quick response.

Perhaps I did a bad job of explaining my initial issue.

The example application in the /SDx_project seems to set the input data, cin, to an all zero array.

If I wanted to change this to take in an input RGB888 384x384 image instead, do I just need to point cin to an array loaded with the image data? 

Or is there pre-processing required? If so, whats needed?

**Comment by atefehsz** [comment]
You need to pre-process the data by changing the data layout of the inputs. If you look more closely, the `mobilenet_preprocess` 
 which is defined [here](https://github.com/UCLA-VAST/FlexCNN/blob/master/SDx_project/src/cnn_sw.cpp#L66) function does this job.
